### ISSUE TITLE
Impl a GenServer Syncer Example to synce NFT by contracts routine and save it by menisa

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai_shang_micro_faas_system#20]
Money: `1000R`

Using key-json pair to save the info. such as: 

> "01": %{owner: 0x0, uri: "xxxx"}

And have a func to get it all.

Ref: 

> https://github.com/WeLightProject/tai_shang_nft_gallery

**Comment by kenspirit** [comment]
没人弄？那我试试看吧。

**Comment by leeduckgo** [comment]
> 没人弄？那我试试看吧。

来😁
