### ISSUE TITLE
add login module & remove btn

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai_shang_micro_faas_system#21]
money: `600R`

requirements: 

add Login module(not need to register now) and remove btn.

see same in:
> https://github.com/WeLightProject/tai_shang_nft_gallery

the remove btn is available only if the user login.
<img width="450" alt="image" src="https://user-images.githubusercontent.com/12784118/164567282-536c37e3-0a22-4418-8f5c-47f45694e91b.png">
And remove the password input:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/12784118/164567331-136f8d0f-7308-4be5-901b-a13fd99dd53a.png">
if logined, user is able to add the tx-id

**Comment by yangcancai** [comment]
Leave it to me (0)

**Comment by leeduckgo** [comment]
> Leave it to me (0)

G00D!
