### ISSUE TITLE
Support to fetch code from codeNFT

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai_shang_micro_faas_system#25]
money: `800R`
See codeNFT on Moonbeam Testnet:
> https://moonbase.moonscan.io/address/0xD1e91A4Bf55111dD3725E46A64CDbE7a2cC97D8a#code

requirements:
- fetch code by the tx_id in NFT
- create an NFT table to related the code fetch from NFT
- impl the adder in code adder page

**Comment by zhenfeng-zhu** [comment]
报名，5.1假期搞一下这个

**Comment by leeduckgo** [comment]
goodgood

**Comment by zhenfeng-zhu** [comment]
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/6822558/166173857-e1e6f06e-7465-4987-be6a-97bb9cf03668.png">

遇到了这个报错，辛苦大狗老师看看

**Comment by leeduckgo** [comment]
fixed.
