### ISSUE TITLE
About Polkadot Hackathon

### ISSUE THREAD

**Issue by 99Kies** [WeLightProject/tai_shang_micro_faas_system#31]
报名链接：https://docs.google.com/forms/d/e/1FAIpQLScR7sGK0XH20jM5zNXy6hc__uIvqhKPxKDetJFsr6WIDE6QNg/viewform?usp=sf_link
Discord参赛群：https://discord.com/invite/KsCEKvqU4p

**Comment by 99Kies** [comment]
![image](https://user-images.githubusercontent.com/45918704/167281395-24d24084-d0d8-4c8a-bcaf-6fdc7fcc08c7.png)

**Comment by leeduckgo** [comment]
Good Job.
