### ISSUE TITLE
NFT Component 完善

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai_shang_micro_faas_system#50]
Money: `700R`

**- 函数1：** 识别 Contract 下的 Address 是否有 NFT；
**- 函数2：** Fetch 该 Address 下的所有 NFT；
**- 函数3：** 识别 Contracts 下的 Address 是否有 NFT；

注：Endpoints 可配置。

可以有存储和不存到本地数据库中两种形式。

**Comment by zhenfeng-zhu** [comment]
举手
