### ISSUE TITLE
Generate API Doc and curl cmd by Click

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai_shang_micro_faas_system#55]
Money: `800R`
![image](https://user-images.githubusercontent.com/12784118/180098726-a03c6380-f53d-48fd-a764-587b3e7974df.png)
Add an btn beside "run code" which named "show the api info"
Then generate an `API DOC` for this func and a `curl cmd`

**Comment by kenspirit** [comment]
我瞅瞅

**Comment by kenspirit** [comment]
https://github.com/WeLightProject/tai_shang_micro_faas_system/wiki/API-Docs#apiv1get_codes

像 wiki 里一样？其中的描述就直接是注释里的内容即可。
然后再加上一条 CURL 命令

生成之后再有一个按钮：叫 Copy as Markdown。
